# Generated by Django 4.2.11 on 2024-03-22 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_full_name_user_groups_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_contact_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Messenger', 'Messenger'), ('Push', 'Push')], max_length=20), size=4, verbose_name='Предпочитаемый способ связи'),
        ),
    ]
