# Generated by Django 4.2.11 on 2024-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_department_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('BLOCKED', 'Заблокирован')], default='ACTIVE', max_length=128, verbose_name='Статус'),
        ),
    ]
