# Generated by Django 4.2.11 on 2024-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='internal_name',
            field=models.CharField(default='Unknown', max_length=128, verbose_name='Внутреннее название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Название'),
        ),
    ]
