# Generated by Django 4.2.11 on 2024-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=256, verbose_name='Наименование приложения-партнера')),
                ('description', models.TextField(blank=True, verbose_name='Описание приложения-партнера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('access_datetime', models.DateTimeField(verbose_name='Срок действия доступа')),
                ('client_secret', models.CharField(blank=True, max_length=64, verbose_name='Код авторизации клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
