# Generated by Django 4.2.11 on 2024-03-26 09:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCommunicationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('communication_limit', models.PositiveSmallIntegerField(default=0, verbose_name='Лимит коммуникаций')),
                ('preferred_mass_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], max_length=20), blank=True, size=4, verbose_name='Предпочитаемый способ массовой связи')),
                ('preferred_personal_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Push', 'Push'), ('Messenger', 'Messenger')], max_length=20), blank=True, size=4, verbose_name='Предпочитаемый способ личной связи')),
            ],
            options={
                'verbose_name': 'Правило коммуникации подразделений',
                'verbose_name_plural': 'Правила коммуникации подразделений',
            },
        ),
    ]
