# Generated by Django 4.2.11 on 2024-03-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication_rules', '0001_initial'),
        ('users', '0002_department_alter_user_options_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcommunicationrule',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.department', verbose_name='Подразделение'),
        ),
    ]
