# Generated by Django 4.2.11 on 2024-03-23 12:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcommunicationrule',
            name='communication_limit',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name='Лимит коммуникаций'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentcommunicationrule',
            name='preferred_mass_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Messenger', 'Messenger'), ('Push', 'Push')], max_length=20), default=['Email', 'Messenger'], size=4, verbose_name='Предпочитаемый способ связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentcommunicationrule',
            name='preferred_personal_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Messenger', 'Messenger'), ('Meeting', 'Meeting'), ('Phone call', 'Phone call')], max_length=20), default=['Messenger', 'SMS', 'Phone call'], size=4, verbose_name='Предпочитаемый способ связи'),
            preserve_default=False,
        ),
    ]
