# Generated by Django 4.2.11 on 2024-03-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication_rules', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentcommunicationrule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='departmentcommunicationrule',
            name='name',
        ),
    ]
