# Generated by Django 4.2.11 on 2024-03-25 18:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_rules', '0002_departmentcommunicationrule_communication_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcommunicationrule',
            name='preferred_mass_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Messenger', 'Messenger'), ('Push', 'Push')], max_length=20), size=4, verbose_name='Предпочитаемый способ массовой связи'),
        ),
        migrations.AlterField(
            model_name='departmentcommunicationrule',
            name='preferred_personal_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Messenger', 'Messenger'), ('Meeting', 'Meeting'), ('Phone call', 'Phone call')], max_length=20), size=4, verbose_name='Предпочитаемый способ личной связи'),
        ),
    ]
