# Generated by Django 4.2.11 on 2024-03-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_department_id_department_internal_name_and_more'),
        ('communication_rules', '0003_alter_departmentcommunicationrule_preferred_mass_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcommunicationrule',
            name='department',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='users.department', verbose_name='Подразделение'),
        ),
    ]
