# Generated by Django 4.2.11 on 2024-03-25 18:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_department_id_department_internal_name_and_more'),
        ('communication_rules', '0004_alter_departmentcommunicationrule_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcommunicationrule',
            name='communication_limit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Лимит коммуникаций'),
        ),
        migrations.AlterField(
            model_name='departmentcommunicationrule',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='departmentcommunicationrule',
            name='preferred_mass_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], max_length=20), blank=True, size=4, verbose_name='Предпочитаемый способ массовой связи'),
        ),
        migrations.AlterField(
            model_name='departmentcommunicationrule',
            name='preferred_personal_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Push', 'Push'), ('Messenger', 'Messenger')], max_length=20), blank=True, size=4, verbose_name='Предпочитаемый способ личной связи'),
        ),
    ]
